/*
 *  tguide — svc_generator.h
 *  written by voidoxin
 *
 *  Service layer for the Script Generator.
 *  Provides ScriptStep struct and buildScript() to compose
 *  multi-step shell scripts from tool templates and custom bash lines.
 */

#pragma once
#include "svc_dto.h"
#include <string>
#include <vector>

// strips shell metacharacters from user input; safe to use from any layer
// see: .ai/security.md — sanitizeInput rule
std::string sanitizeInput(const std::string& input);

namespace SvcGenerator {

    // ── Script Step ──────────────────────────────────────────────────────
    // Represents one step in a generated script sequence.

    enum class StepType {
        TEMPLATE_COMMAND,   // a tool template with target/port filled in
        BASH_LINE           // a raw bash line inserted by the user
    };

    struct ScriptStep {
        StepType type;
        int      toolId      = -1;       // valid for TEMPLATE_COMMAND
        int      templateId  = -1;       // valid for TEMPLATE_COMMAND
        std::string target;              // valid for TEMPLATE_COMMAND
        std::string port;                // valid for TEMPLATE_COMMAND
        std::string toolName;            // display name, populated at creation
        std::string templateName;        // display name, populated at creation
        std::string bashLine;            // valid for BASH_LINE
    };

    // ── Build Script ─────────────────────────────────────────────────────
    // Takes a sequence of steps and produces the final script string.
    // Each TEMPLATE_COMMAND step produces one command via SvcTools::buildCommand().
    // Each BASH_LINE step inserts the line verbatim.
    //
    // The output has:
    //   #!/bin/bash
    //   # Generated by tguide on YYYY-MM-DD
    //   # Steps: N
    //   <blank line>
    //   <command 1>
    //   <bash line 1>
    //   <command 2>
    //   ...
    std::string buildScript(const std::vector<ScriptStep>& steps);

} // namespace SvcGenerator
