/*
 *  tguide — svc_generator.cpp
 *  written by voidoxin
 *
 *  Service layer for the Script Generator.
 *  Connects to SvcTools::buildCommand() and PathResolver.
 */

#include "../includes/svc_generator.h"
#include "../includes/svc_tools.h"
#include "../../L0-core/include/path_resolver.h"
#include <ctime>
#include <sstream>
#include <vector>

using namespace std;

// strips shell metacharacters from user input to prevent command injection
string sanitizeInput(const string& input) {
    string result;
    result.reserve(input.size());
    for (char c : input) {
        if (c == ' ' || c == ';' || c == '|' || c == '&' ||
            c == '$' || c == '>' || c == '<' ||
            c == '`' || c == '\n' || c == '\r' ||
            c == '\'' || c == '"' || c == '\\' ||
            c == '(' || c == ')' || c == '{' || c == '}' ||
            c == '!' || c == '~' || c == '*' || c == '?' ||
            c == '[' || c == '#')
            continue;
        result += c;
    }
    return result;
}

namespace SvcGenerator {

string buildScript(const vector<ScriptStep>& steps) {
    ostringstream out;

    // ── shebang ──
    out << "#!/bin/bash\n";

    // ── metadata header ──
    time_t now = time(nullptr);
    char dateBuf[32];
    struct tm local;
    localtime_r(&now, &local);
    strftime(dateBuf, sizeof(dateBuf), "%Y-%m-%d", &local);
    out << "# Generated by tguide on " << dateBuf << "\n";
    out << "# Steps: " << steps.size() << "\n";
    out << "\n";

    // ── steps ──
    for (size_t i = 0; i < steps.size(); i++) {
        const auto& step = steps[i];

        out << "# ----- step " << (i + 1);

        if (step.type == StepType::TEMPLATE_COMMAND) {
            out << " : " << step.toolName << " / " << step.templateName;
        } else {
            out << " : custom bash";
        }
        out << " -----\n";

        if (step.type == StepType::TEMPLATE_COMMAND) {
            SvcDTO::ToolDTO tool = SvcTools::getToolById(step.toolId);
            SvcDTO::TemplateDTO tmpl;
            // find the template from the tool's template list
            auto tmpls = SvcTools::getTemplatesByToolId(step.toolId);
            for (const auto& t : tmpls) {
                if (t.id == step.templateId) { tmpl = t; break; }
            }
            string cmd = SvcTools::buildCommand(tool, tmpl, step.target, step.port);
            out << cmd << "\n";
        } else {
            out << step.bashLine << "\n";
        }
        out << "\n";
    }

    return out.str();
}

} // namespace SvcGenerator
